default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
